GET https://books.ioasys.com.br/api/v1/auth/lo
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDE3MTYzYWZhZjVkZTIyYjgwNGExNzMiLCJ2bGQiOjE2MTgzNjMxODc2NDQsImlhdCI6MTYxODM2Njc4NzY0NH0.z4ShnQOHtM6LfhUYu5eHea6LBN9P3FbzfdSuGxZiZJ0




